:scrollbar:
:numbered:
= Red Hat OpenShift Virtualization workshop

[%hardbreaks]

== はじめに

OpenShift Virtualization は、最新の Kubernetes ベースのインフラストラクチャ上に仮想マシンを導入することを可能にします。新しいアプリケーションの開発と提供、および既存のアプリケーションのモダナイゼーションを可能にし、仮想マシン、コンテナ、サーバレス機能で構成されるアプリケーションを、Kubernetes ネイティブのツールとパラダイムを使用してすべて一緒に管理することができます。


== ワークショップモジュール

このワークショップは、標準モジュールとオプションモジュールの 2 つの分かれています。標準モジュールだけでも有意義ですが、時間が許す限りオプションも含め全てのモジュールを受講していただくことをお勧めします。

=== 標準モジュール
このワークショップには2つの標準モジュールがあります。

. *OpenShift Virtualization の基礎* : +
このラボでは、OpenShift Virtualization で仮想マシンを作成して使用する方法に焦点を当てます。ラボの中では、Linux と Windows の両方の VM を作成します。また、VM を実行する際に最も重要なコンセプトの1つである、既存のディスクイメージから VM を実行し、VM をカスタマイズする機能について紹介します。
VM の管理者 / ユーザとして実行ことが多いであろう、最も一般的なタスクをカバーしています。
. *仮想マシンの移行 (Migration Toolkit for Virtualization)* : +
このセクションでは、Migration Toolkit for Virtualization (MTV) を使用して、既存の VMware vSphere 環境から OpenShift Virtualization にいくつかの VM を移行します。

=== オプションモジュール

さらに、いくつかのオプションのモジュールがあります。 +
主に仮想インフラ管理者向けの内容であり、これらを受講することでさらに OpenShift Virtualization による仮想化の理解が深まります。
それぞれのモジュールは前後関係があるため、上から順番に受講してください。

* *ベアメタル OpenShift の概要* : +
OpenShift のノードとリソースの管理は、あなたが慣れ親しんでいる仮想インフラのものとは異なります。このモジュールでは、サーバハードウェアの責任者である場合に重要な OpenShift のいくつかの側面と概念について説明します。
* *ネットワーク管理* : +
OpenShift Virtualization の仮想マシンは、デフォルトでは OpenShift 内部の SDN (Software-defined Network) に接続します。このセクションでは、VM を VLAN のような外部の物理ネットワークに接続する方法を説明します。
* *ストレージ管理* : +
このモジュールでは、OpenShift 上のストレージの基礎と、OpenShift Virtualization がいくつかのマシンイメージのブートソースを自動的に提供する方法を紹介します。このモジュールでは、スナップショットを使った操作の実行方法と、VM のクローンを作成する方法も紹介します。
////
* *テンプレートの管理* : +
仮想マシンのデプロイを効率化するために、管理者は多くの場合、デプロイ作業を容易にするためのテンプレートを作成します。このセクションでは、そのプロセスに焦点を当てます。
////
* *バックアップとリストア* : +
仮想マシンとそのデータを保護することは、パフォーマンスと可用性と同じくらい重要です。このラボでは、OpenShift API for Data Protection (OADP) がストレージに依存しない方法で VM を保護する方法を紹介します。

////
=== 仮想マシン管理者／ユーザ向けモジュール

* *Route を使ったアプリケーションの公開* : +
このラボでは、Service と Route を使用してアプリケーション・コンポーネント間を内部で接続し、アプリケーションのフロントエンドのみを外部に公開するプロセスについて説明します。
* *MetalLB を使ったアプリケーションの公開* : +
VM を外部の L2 ネットワークに置くことなく、VM にホストされたアプリケーションに接続性を提供することは、アプリケーションへの接続性を管理する強力な方法です。このラボでは、VM を外部ネットワークに接続することなく、データベースだけを外部に公開するプロセスを説明します。
////

== OpenShift Virtualization とは

* OpenShift Virtualization は Red Hat OpenShift の機能であり、アドオンや別の製品ではなく、すべての OpenShift ユーザが使用可能です。
* 現在および将来の全ての OpenShift ユーザーには、OpenShift サブスクリプションの一部として OpenShift Virtualization が提供されます。OpenShift 4.5 以降、利用可能です。
* OpenShift Virtualization は、Cloud Native Computing Foundation (CNCF) のサンドボックスプロジェクトである KubeVirt プロジェクトで開発されている "conatiner-native virtualization" 技術に基づいています。
* OpenShift Virtualization は、Red Hat Enterprise Linux KVM ハイパーバイザを活用しています。このハイパーバイザは、世界中の多くの組織やクラウドサービスプロバイダで使用されており、15 年以上にわたって開発が続けられている、成熟した高性能なオープンソースのハイパーバイザです。
* OpenShift Virtualization は RHEL KVM ハイパーバイザを活用し、VM を Kubernetes と KubeVirt で管理できるようにする。OpenShift Virtualization VM は、Kubernetes のスケジューリング、ネットワーク、ストレージのインフラを使用します。
* OpenShift Virtualization には、**無制限の仮想 RHEL ゲスト**用のエンタイトルメントが含まれています。他のサポートされているオペレーティングシステムのゲストライセンスは別途購入する必要があります。
* OpenShift Virtualization は、Red Hat の他の KVM 仮想化製品に適用されるものと同じルールに従って、Windows ゲストのサポートについて Microsoft の SVVP 認証を受けています。
* OpenShift Virtualization は、通常オンプレミスまたは専用ホスティングのベアメタル物理サーバ上でのみサポートされます。その他のトポロジー (Red Hat Virtualization や VMware vSphere のような仮想化インフラストラクチャ上の OpenShift、パブリッククラウド上の OpenShift) のサポートは、現時点ではサポートされていません。
* https://www.redhat.com/en/blog/managing-virtual-machines-and-containers-as-code-with-openshift-virtualization-on-red-hat-openshift-service-on-aws[AWS / ROSA^] でのサポートも発表されています。追加のマネージド OpenShift クラウドサービスでの OpenShift Virtualization のサポートも追加しているところです。

== 従来の VM プラットフォームから移行する理由

**クラウドネイティブな開発／運用の実現** +
Red Hat OpenShift は、スピード、俊敏性、信頼性、そして幅広い選択肢を備えたアプリケーションの構築を支援します。構築する場所を選ばず、本番さながらの開発環境でコーディングができ、本来の業務に専念できます。

**完全なアプリケーション開発スタック** +
Red Hat OpenShift Dev Spaces (旧称 Red Hat CodeReady Workspaces) 、ランタイム、インテグレーションとプロセス自動化、サーバレス、パイプラインなど、全体を通してセキュリティが確保されています。

**インフラのコストをイノベーションに転換** +
OpenShift ネイティブ・アーキテクチャは、レガシーな SDDC (Software-Defined Data Center) の重い構造から、軽量なコンテナ・ネイティブ・フレームワークへと変化させます。

**リスクの低減** +
OpenShift はオンプレミスとパブリッククラウドのオプションをサポートしており、パブリッククラウドのロックインに対する保険になります。

**インフラへの非依存** +
Red Hat OpenShift は、ベアメタル、オンプレミスの仮想環境、あるいはパブリッククラウド上で一貫性をもって稼働し、デプロイとアップデートの究極の選択肢と柔軟性を提供します。

**ピュアなオープンソースイノベーション** +
Kubernetes、サーバレス、サービスメッシュ、Kubernetes Operators などのイノベーションは、Red Hat を筆頭とするオープンソースの開発スピードによってもたらされます。

== Next steps

さらに OpenShift Virtualization について知りたい方は、次の情報ソースをご覧ください。

* https://www.redhat.com/ja/technologies/cloud-computing/openshift/virtualization[Red Hat OpenShift Virtualization Landing Page]
* https://docs.openshift.com/container-platform/latest/virt/about_virt/about-virt.html[OpenShift documentation], 
* https://www.youtube.com/playlist?list=PLaR6Rq6Z4IqeQeTosfoFzTyE_QmWZW6n_[YouTube Playlist].

